export default {
    userexist:"User already exist",
    emailexist:"Email already exist",
    phoneexist:"Phone number already exist",
    genderproper:"Give a proper Gender",
    invalidusername:"Invalid Username",
    invalidpassword:"Invalid Password",
    servererror:"Server Error",
    invalidemail:"Invalid email",
    otpnotgenerating:"Server error during OTP generation",
    emailnotfound:"Email is not found",
    passwordlength:"Password must be at least 8 characters long.",
    passwordcharacters:"Password must contain at least one uppercase letter, one lowercase letter, and one number",
    samepassworderrror:"You have entered your old password. Please use a different password.",
    newandconfirmpassworderror:"New password and confirm password do not match.",
    passwordupdated: "Password updated successfully.",
    passwordupdfailure:"Failed to update password. Please try again.",
    passwordupderror:"An error occurred while updating the password.",
    otpverified:"OTP verified",
    otpfailure:"Give a correct OTP",
    usernotfound:"User not found",
    userupdated:"User updated successfully",
    imagefailure:"Give an image",
    usercreateerror:"There was an error creating the user",
    passwordnotmatch:"Passwords do not match"
}